spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: user
        password: password
        template:
            retry:
                enabled: true
                max-attempts: 5
                initial-interval: 3s
    cache:
        type: redis
    data:
        redis:
            host: localhost
            port: 6379