spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: user
        password: password
        template:
            retry:
                enabled: true
                max-attempts: 5
                initial-interval: 3s